In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
#Load dataset automobile_data.csv file
#Load dataset automobile_data.csv file
df = pd.read_csv('Automobile_data It vedant.csv')

In [3]:
#To display first 5 records
df.head()

symboling normalized-losses         make fuel-type   body-style  \
0          3                 ?  alfa-romero       gas  convertible   
1          3                 ?  alfa-romero       gas  convertible   
2          1                 ?  alfa-romero       gas    hatchback   
3          2               164         audi       gas        sedan   
4          2               164         audi       gas        sedan   

  drive-wheels engine-location  width  height engine-type  engine-size  \
0          rwd           front   64.1    48.8        dohc          130   
1          rwd           front   64.1    48.8        dohc          130   
2          rwd           front   65.5    52.4        ohcv          152   
3          fwd           front   66.2    54.3         ohc          109   
4          4wd           front   66.4    54.3         ohc          136   

  horsepower  city-mpg  highway-mpg  price  
0        111        21           27  13495  
1        111        21           27  16500  
2        154        19           26  16500  
3        102        24           30  13950  
4        115        18           22  17450

In [4]:
#First check null values
df.isnull().sum()

symboling            0
normalized-losses    0
make                 0
fuel-type            0
body-style           0
drive-wheels         0
engine-location      0
width                0
height               0
engine-type          0
engine-size          0
horsepower           0
city-mpg             0
highway-mpg          0
price                0
dtype: int64

In [5]:
df.dtypes

symboling              int64
normalized-losses     object
make                  object
fuel-type             object
body-style            object
drive-wheels          object
engine-location       object
width                float64
height               float64
engine-type           object
engine-size            int64
horsepower            object
city-mpg               int64
highway-mpg            int64
price                  int64
dtype: object

In [6]:
c=0
for i,data in enumerate(df['normalized-losses']):
    if not data.isnumeric():
        c=c+1
        print(i," " ,data)
print("No. of special chars : ",c)

0   ?
1   ?
2   ?
5   ?
7   ?
9   ?
14   ?
15   ?
16   ?
17   ?
43   ?
44   ?
45   ?
46   ?
48   ?
49   ?
63   ?
66   ?
71   ?
73   ?
74   ?
75   ?
82   ?
83   ?
84   ?
109   ?
110   ?
113   ?
114   ?
124   ?
126   ?
127   ?
128   ?
129   ?
130   ?
131   ?
181   ?
189   ?
191   ?
192   ?
193   ?
No. of special chars :  41


In [7]:
#Replace '?' of normalised-losses with null values permanent
df["normalized-losses"].replace("?",np.nan,inplace=True)
#syntaX: replace("old value","new value",inplace=True)

In [8]:
#To check null values
df.isnull().sum()

symboling             0
normalized-losses    41
make                  0
fuel-type             0
body-style            0
drive-wheels          0
engine-location       0
width                 0
height                0
engine-type           0
engine-size           0
horsepower            0
city-mpg              0
highway-mpg           0
price                 0
dtype: int64

In [9]:
#To change the datatype of normalized-losses from object to float
#permanent : use inbuilt method astype()
df["normalized-losses"]=df["normalized-losses"].astype("float")

In [10]:
#Fill null values with average/mean of normalized-losses column in 
#normalized-losses column permanent
m=df["normalized-losses"].mean()
df["normalized-losses"].fillna(m,inplace=True)

In [11]:
c=0
for i,data in enumerate(df['horsepower']):
    if not data.isnumeric():
        c=c+1
        print(i," " ,data)
print("No. of special chars : ",c)

130   ?
131   ?
No. of special chars :  2


In [12]:
#Replace '?' of horsepower with null values permanent
df["horsepower"].replace("?",np.nan,inplace=True)

In [13]:
df.isnull().sum()

symboling            0
normalized-losses    0
make                 0
fuel-type            0
body-style           0
drive-wheels         0
engine-location      0
width                0
height               0
engine-type          0
engine-size          0
horsepower           2
city-mpg             0
highway-mpg          0
price                0
dtype: int64

In [14]:
#To change the datatype of horsepower   from object to float
#permanent : use inbuilt method astype()
df["horsepower"]=df["horsepower"].astype("float")

In [15]:
#Fill null values with average/mean of horsepower column in 
#horsepower column permanent
m=df["horsepower"].mean()
df["horsepower"].fillna(m,inplace=True)

In [16]:
#again check null values in given dataset
df.isnull().sum()

symboling            0
normalized-losses    0
make                 0
fuel-type            0
body-style           0
drive-wheels         0
engine-location      0
width                0
height               0
engine-type          0
engine-size          0
horsepower           0
city-mpg             0
highway-mpg          0
price                0
dtype: int64

In [17]:
df.dtypes

symboling              int64
normalized-losses    float64
make                  object
fuel-type             object
body-style            object
drive-wheels          object
engine-location       object
width                float64
height               float64
engine-type           object
engine-size            int64
horsepower           float64
city-mpg               int64
highway-mpg            int64
price                  int64
dtype: object

In [18]:
#separate numerical type column and object type column and store in new dataset
df_num=df.select_dtypes(["int64","float64"])#hold to int and float type data 
df_cat=df.select_dtypes(object)#hold object type data

In [19]:
df_num.dtypes

symboling              int64
normalized-losses    float64
width                float64
height               float64
engine-size            int64
horsepower           float64
city-mpg               int64
highway-mpg            int64
price                  int64
dtype: object

In [20]:
df_cat.dtypes

make               object
fuel-type          object
body-style         object
drive-wheels       object
engine-location    object
engine-type        object
dtype: object

In [21]:
#change the object type data into numerical type then use LabelEncoder class
from sklearn.preprocessing import LabelEncoder

In [22]:
for col in df_cat :
    le=LabelEncoder() #create the object of LabelEncoder class
    df_cat[col]=le.fit_transform(df_cat[col])

In [23]:
df_cat.head()

make  fuel-type  body-style  drive-wheels  engine-location  engine-type
0     0          1           0             2                0            0
1     0          1           0             2                0            0
2     0          1           2             2                0            5
3     1          1           3             1                0            3
4     1          1           3             0                0            3

In [24]:
#concatenation of both dataset df_num and df_cat and hold new dataset df_new
df_new=pd.concat([df_num,df_cat],axis=1) #axis=1 column wise
df_new.head()

symboling  normalized-losses  width  height  engine-size  horsepower  \
0          3              122.0   64.1    48.8          130       111.0   
1          3              122.0   64.1    48.8          130       111.0   
2          1              122.0   65.5    52.4          152       154.0   
3          2              164.0   66.2    54.3          109       102.0   
4          2              164.0   66.4    54.3          136       115.0   

   city-mpg  highway-mpg  price  make  fuel-type  body-style  drive-wheels  \
0        21           27  13495     0          1           0             2   
1        21           27  16500     0          1           0             2   
2        19           26  16500     0          1           2             2   
3        24           30  13950     1          1           3             1   
4        18           22  17450     1          1           3             0   

   engine-location  engine-type  
0                0            0  
1                0            0  
2                0            5  
3                0            3  
4                0            3

In [25]:
df_new.dtypes

symboling              int64
normalized-losses    float64
width                float64
height               float64
engine-size            int64
horsepower           float64
city-mpg               int64
highway-mpg            int64
price                  int64
make                   int32
fuel-type              int32
body-style             int32
drive-wheels           int32
engine-location        int32
engine-type            int32
dtype: object

In [26]:
import os
os.getcwd()

'C:\\Users\\yuvra'

In [27]:
#select input & output from df_new
X=df_new.drop("price",axis=1)   #input 
Y=df_new['price']    #output

In [28]:
#train test split 
from sklearn.model_selection import train_test_split

#create objects of inbuilt class train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.30,random_state=1)

In [29]:
X_train.shape,X_test.shape

((143, 14), (62, 14))

In [30]:
#apply StandardScaler on input X_train
from sklearn.preprocessing import StandardScaler
#create object of StandardScaler class
ss=StandardScaler()
X_train=ss.fit_transform(X_train)  #converts 2D numpy array
#apply scaling on testing inputX_test
X_test=ss.transform(X_test)  #converts 2D numpy array

In [31]:
#perform the model with LinearRegression Algorithm
#train the model with 70% data with help of LinearRegression class
from sklearn.linear_model import LinearRegression 

In [32]:
#create object of LinearRegression 
lr=LinearRegression()

In [33]:
#train the model from training data X_train , Y_train 70% : use inbuilt method 
#of LinearRegression class : fit()
lr.fit(X_train,Y_train)

LinearRegression()

In [34]:
#to check slope of each input
lr.coef_

array([   57.81895665,    44.47885193,  1700.08139295,   918.27940669,
        4046.25518791,  -450.43882012,  1968.72478882, -2781.47379917,
       -1253.87858019,  -178.99929397,  -149.85563859,  1058.52249069,
        2352.26450278,   309.65276269])

In [35]:
dict={'Input Columns': X.columns,'Slope':lr.coef_}
df1=pd.DataFrame(dict)
df1

Input Columns        Slope
0           symboling    57.818957
1   normalized-losses    44.478852
2               width  1700.081393
3              height   918.279407
4         engine-size  4046.255188
5          horsepower  -450.438820
6            city-mpg  1968.724789
7         highway-mpg -2781.473799
8                make -1253.878580
9           fuel-type  -178.999294
10         body-style  -149.855639
11       drive-wheels  1058.522491
12    engine-location  2352.264503
13        engine-type   309.652763

In [36]:
#check intercept
lr.intercept_

13483.55944055944

In [37]:
#test the model with 30% data
Y_pred=lr.predict(X_test)       #Y_pred=m1*X1+m2*X2+.......+m14*X14+c
Y_pred

array([ 6147.97177535,  6877.02018581,  5163.92272988,  6529.64152282,
        9097.48416127, 26360.34172002,  7459.86435141,   877.82049881,
        5144.01614104, 13519.72327075, 15450.90944825, 14432.86068487,
       16383.3823446 , 11141.26580437, 16456.45835103, 13899.96152052,
        7470.89015168,  8822.10978266, 10871.71907185,  7575.62315193,
       10982.8020501 ,  6830.55418791, 13695.54356268,  6367.05540369,
       13729.72634597,  8822.10978266, 15020.54539526,  6519.17466513,
        4748.87641153,  9309.57917764,  8168.78349461, 14331.33093265,
       25640.12934796, 11908.15949477, 19763.97916514,  6562.05039495,
        8169.68530317, 30669.00442191,  9815.72891291, 16913.4988703 ,
        6488.35956878, 20293.75457963,  7703.43107067,  8440.48221513,
        8644.09950215,  7183.23963857, 40496.63165103,  7556.38024834,
       17202.53531151, 18961.11466889, 26165.68818112, 16952.9687522 ,
       21835.40141131,  6217.42536906, 13103.73962425,  7263.42333164,
      

In [38]:
#find the training score: score() inbuilt method of LinearRegression class 
lr.score(X_train,Y_train)     #score between 0-1

0.8504573774895473

In [39]:
#find the testing score
lr.score(X_test,Y_test)     #or r2_score(Y_test,Y_pred)

0.7965566780397382

In [40]:
#here training score > testing score but the difference is 6 , means model is overfit
#to overcome overfitting problem, use regularisation means add some external error during training time 
#how to take care of ovefitting:
#1. L1 means Lasso Regularisation 
#2. L2 means Ridge Regularisation

In [41]:
''' Add some error during training time 
   1. Lasso Regularization : L1  
   RSS+lambda*sum(abs(all coefficient)) here lambda is also known as 
   hyper-parameter, value of lambda  can be 200,400,600,..1000
   2. Ridge Regularization : L2
   RSS+lambda*sum(square(all coefficient)) here lambda is also known as 
   hyper-parameter, value of lambda  can be 0 to 50
    '''

' Add some error during training time \n   1. Lasso Regularization : L1  \n   RSS+lambda*sum(abs(all coefficient)) here lambda is also known as \n   hyper-parameter, value of lambda  can be 200,400,600,..1000\n   2. Ridge Regularization : L2\n   RSS+lambda*sum(square(all coefficient)) here lambda is also known as \n   hyper-parameter, value of lambda  can be 0 to 50\n    '

In [42]:
#Use Lasso Regularisation
#inbuilt method Lasso
from sklearn.linear_model import Lasso

In [43]:
#create object of Lasso class 
L1=Lasso(200)  #passing value of lambda when create the object of Lasso class
    #train the model with 70% data with help of Lasso,use fit() inbuilt method Lasso class
L1.fit(X_train,Y_train)
#test model with 30% data with help of Lasso ,use predict inbuilt method Lasso class
Y_pred=L1.predict(X_test)
#find the training score of model 
train_score=L1.score(X_train,Y_train)
#find testing score of model 
test_score=L1.score(X_test,Y_test)
print("Training Score :{} and Test Score :{}".format(train_score,test_score))

Training Score :0.8410262816516455 and Test Score :0.8111395722615142


In [44]:
#to check slope means coefficient 
L1.coef_

array([  -0.        ,    0.        , 1526.47716035,  676.38215667,
       3934.38934048,   -0.        ,   -0.        , -740.16761112,
       -983.39924513, -206.48143873,   -0.        ,  845.33429279,
       1971.83096928,  146.23115572])

In [45]:
#add new column in existing dataset df1
df1['slope_Lasso']=L1.coef_
df1

Input Columns        Slope  slope_Lasso
0           symboling    57.818957    -0.000000
1   normalized-losses    44.478852     0.000000
2               width  1700.081393  1526.477160
3              height   918.279407   676.382157
4         engine-size  4046.255188  3934.389340
5          horsepower  -450.438820    -0.000000
6            city-mpg  1968.724789    -0.000000
7         highway-mpg -2781.473799  -740.167611
8                make -1253.878580  -983.399245
9           fuel-type  -178.999294  -206.481439
10         body-style  -149.855639    -0.000000
11       drive-wheels  1058.522491   845.334293
12    engine-location  2352.264503  1971.830969
13        engine-type   309.652763   146.231156

In [46]:
#check intercept
L1.intercept_

13483.55944055944

In [47]:
#Find training score of model 
train_score=L1.score(X_train,Y_train)
#find testing score of model 
test_score=L1.score(X_test,Y_test)
print("Value of Hyper-parameter Lambda: 200")
print("Training score : ",train_score)
print("Testing score : ",test_score)

Value of Hyper-parameter Lambda: 200
Training score :  0.8410262816516455
Testing score :  0.8111395722615142


In [48]:
#Ridge regularisation 
#inbuilt method Ridge
from sklearn.linear_model import Ridge

In [49]:
# #in Ridge : RSS+lambda *sum(all slope**2)
# #here Value of Lambda between 0 to 50 
# #create object of Lasso class 
# ''''for i in range(0,51,1):     #i=1 
#     L2=Ridge(i)  #passing value of lambda when create the object of Lasso class
#     #train the model with 70% data with help of Lasso,use fit() inbuilt method Lasso class
#     L2.fit(X_train,Y_train)
#     #test model with 30% data with help of Ridge ,use predict inbuilt method Lasso class
#     Y_pred=L2.predict(X_test)
#     #find the training score of model 
#     train_score=L2.score(X_train,Y_train)
#     #find testing score of model 
#     test_score=L2.score(X_test,Y_test)
#     print("Value of Hyper-parameter Lambda: ",i)
#     print("Training Score :{} and Test Score :{}".format(train_score,test_score))
#     print("*****************************************************************")

In [50]:
#correct value of lambda is 12 

In [51]:
L2=Ridge(12)  #passing value of lambda when create the object of Lasso class
#train the model with 70% data with help of Lasso,use fit() inbuilt method Lasso class
L2.fit(X_train,Y_train)
#test model with 30% data with help of Ridge ,use predict inbuilt method Lasso class
Y_pred=L2.predict(X_test)
#find the training score of model 
train_score=L2.score(X_train,Y_train)
#find testing score of model 
test_score=L2.score(X_test,Y_test)
print("Value of Hyper-parameter Lambda: 12")
print("Training score : ",train_score)
print("Testing score : ",test_score)

Value of Hyper-parameter Lambda: 12
Training score :  0.8432726575220612
Testing score :  0.8101604250480487


In [52]:
#to check slope means coefficient after apply ridge
L2.coef_

array([ -104.29485504,    31.99752156,  1545.69455186,   913.49363882,
        3304.10521033,   212.50192744,   149.18346022, -1141.97673267,
       -1160.9432078 ,  -447.01080966,  -277.19719497,  1023.47169112,
        1980.40727127,   395.91276326])

In [53]:
#add new column in existing dataset df1
df1['slope_Ridge']=L2.coef_
df1

Input Columns        Slope  slope_Lasso  slope_Ridge
0           symboling    57.818957    -0.000000  -104.294855
1   normalized-losses    44.478852     0.000000    31.997522
2               width  1700.081393  1526.477160  1545.694552
3              height   918.279407   676.382157   913.493639
4         engine-size  4046.255188  3934.389340  3304.105210
5          horsepower  -450.438820    -0.000000   212.501927
6            city-mpg  1968.724789    -0.000000   149.183460
7         highway-mpg -2781.473799  -740.167611 -1141.976733
8                make -1253.878580  -983.399245 -1160.943208
9           fuel-type  -178.999294  -206.481439  -447.010810
10         body-style  -149.855639    -0.000000  -277.197195
11       drive-wheels  1058.522491   845.334293  1023.471691
12    engine-location  2352.264503  1971.830969  1980.407271
13        engine-type   309.652763   146.231156   395.912763

In [54]:
#Find training score of model 
train_score=L2.score(X_train,Y_train)
#find testing score of model 
test_score=L2.score(X_test,Y_test)
print("Value of Hyper-parameter Lambda: 121")
print("Training score : ",train_score)
print("Testing score : ",test_score)

Value of Hyper-parameter Lambda: 121
Training score :  0.8432726575220612
Testing score :  0.8101604250480487


In [55]:
# in lasso : right value o flambda int his daaraset = 200 ans score = 81%
# in ridge : rght value of lambda in this dataset = 12 & score = 81%
# score is same in Lasso and Ridge, how to decide lasso is better than ridhe 
#sp we need to apply cross validation we use inbuit cross cross_val_score
from sklearn.model_selection import cross_val_score

In [56]:
# nOW APPLY CROSS VALIDATION ON lASSO
#first create the object of lasso class
L1= Lasso(200)

In [57]:
# create the object of cross validation
cross_Lasso = cross_val_score(L1,X,Y,cv = 4)
#cross_val_score9object of Lasso clas,input,output,no of partitioon of dataset)
#cv is to specify the number of partitions to be made


In [58]:
# score after iteration k()
print(cross_Lasso)

[0.76560829 0.81872367 0.43344753 0.448364  ]


In [59]:
# to find the average of mean of all scores
ml = cross_Lasso.mean()
print('Average score in Lasso',ml)

Average score in Lasso 0.6165358705430691


In [60]:
#first create the object of ridge class
L2= Ridge(12)

In [61]:
# create the object of cross validation
cross_Ridge = cross_val_score(L2,X,Y,cv = 4)
#cross_val_score9object of Lasso clas,input,output,no of partitioon of dataset)
#cv is to specify the number of partitions to be made

In [62]:
print(cross_Ridge)

[0.7425055  0.85923003 0.41004375 0.45232333]


In [63]:
ml = cross_Ridge.mean()
print('Average score in Lasso',ml)

Average score in Lasso 0.6160256545421423


In [64]:
# in lassso mean = 0.6165
# in ridge mean = 0.6160
